### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by matheusidt** [matheusidt/ADS-GRUPO-04#1]
## Como usuário necessito de uma tela de login para ter acesso ao sistema

- [x] Design da tela
- [x] Documentação
- [x] Codificação da tela login (Estruturação da tela, Estilização, Funcionalidades)
- [x] Integralizar banco de dados para reconhecer acesso do usuário 

Critérios de aceite:

- [x] Inputs reconhecendo os textos
- [x] Botão de "Logar" funcionando
- [x] Verificar se as cores usadas estão com boa acessibilidade
- [x] Caso os dados estejam incorretos, aparecer notificação de erro
- [x] Caso os dados estejam corretos ir para a próxima tela

Definição de pronto:
Como usuário, consigo ter uma tela onde consigo inserir meus dados para conseguir ter acesso ao sistema

**Comment by matheusidt** [comment]
Foi adicionado os critérios de aceite e a definição de pronto

**Comment by davifma** [comment]
Onde estão o design e a documentação?

**Comment by matheusidt** [comment]
A gente se desfez daquele design e começamos a criar outro. Em breve colocamos aqui.

**Comment by matheusidt** [comment]
[Print login](https://github.com/matheusidt/ADS-GRUPO-04/blob/main/Prints/371323475-dea166c4-2fda-4eaf-94c1-01160b023ad0.png)

**Comment by matheusidt** [comment]
[Fluxograma](https://github.com/matheusidt/ADS-GRUPO-04/blob/main/Prints/Flowchart%20(1).jpg)

**Comment by davifma** [comment]
Tá falando que foi codificado, como eu acesso?

**Comment by matheusidt** [comment]
https://miguelraveli.github.io/adsgrupo4/#/

**Comment by matheusidt** [comment]
[Documentação Login](https://github.com/matheusidt/ADS-GRUPO-04/tree/main/Documentação%20Login)

**Comment by davifma** [comment]
Fluxograma não carrega
https://miguelraveli.github.io/adsgrupo4/#/  não carrega
Tente usar os símbolos corretos nos diagramas

Eu inseri um e-mail e o nome está errado?

![Image](https://github.com/user-attachments/assets/7945768b-8911-4066-9deb-501ec19f1977)

Toda a documentação foi inserida de ultima hora o que indica que não estava havendo acompanhamento do projeto até então.
