### ISSUE TITLE
Cadastro

### ISSUE THREAD

**Issue by matheusidt** [matheusidt/ADS-GRUPO-04#2]
## Como usuário eu preciso fazer o meu cadastro para ter acesso ao sistema

- [x] Design da tela;
- [ ] Documentação ;
- [x] Codificação (Estruturação, Estilização, Funcionalidades);
- [x] Conexão com banco de dados para consultar informações do usuário.

Critérios de aceite:

- [x] Inputs reconhecendo os textos;
- [x] Botão de "Cadastrar" funcionando;
- [x] Botão de "Voltar" funcionando;
- [x] Verificar se as cores usadas estão com boa acessibilidade;
- [x] Caso esteja tudo preenchido corretamente ir para a tela de login.

Definição de pronto:
Eu como usuário, consigo criar um cadastro dentro do sistema para que eu consiga ter acesso a plataforma.

**Comment by matheusidt** [comment]
Foi adicionado os critérios de aceite e a definição de pronto

**Comment by davifma** [comment]
Está tudo concluído menos a documentação, onde está o link para verificação?

**Comment by matheusidt** [comment]
[Documentação Cadastro](https://github.com/matheusidt/ADS-GRUPO-04/tree/main/Documentação%20Cadastro)
